apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingressPrefix }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 8080
